# Generated by Django 2.0.3 on 2018-04-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panasonic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='banner_mark',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='chat_url',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='page_logo',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='secondary_color',
        ),
    ]
