# Generated by Django 2.0.3 on 2018-04-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panasonic', '0003_auto_20180425_0610'),
        ('panasonic', '0007_auto_20180426_0012'),
    ]

    operations = [
    ]
