# Generated by Django 2.0.3 on 2018-05-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panasonic', '0011_auto_20180504_0838'),
        ('panasonic', '0012_auto_20180503_0611'),
    ]

    operations = [
    ]
