# Generated by Django 2.0.3 on 2018-05-14 06:25

import datasheet.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('panasonic', '0015_auto_20180510_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetpage',
            name='sheet_blocks',
            field=wagtail.core.fields.StreamField((('grid', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('json_data', datasheet.blocks.JSONTextBlock(required=False))))), ('selector', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('json_data', datasheet.blocks.JSONTextBlock(required=False))))), ('dimension', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())))), ('chart', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock(require=False)), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('bar', 'Bar'), ('column', 'Column'), ('line', 'Line'), ('spline', 'Spline')], require=False)), ('legend', wagtail.core.blocks.CharBlock(required=False)), ('x_axis', wagtail.core.blocks.CharBlock(required=False)), ('y_axis', wagtail.core.blocks.CharBlock(required=False)), ('chart_values', datasheet.blocks.JSONTextBlock(required=False))))), ('characteristics', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(default='Characteristics')), ('subtitle', wagtail.core.blocks.CharBlock(require=False)), ('bookmark', wagtail.core.blocks.CharBlock(default='characteristics')), ('charts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(default='', required=False)), ('subtitle', wagtail.core.blocks.CharBlock(default='', require=False)), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('bar', 'Bar'), ('column', 'Column'), ('line', 'Line'), ('spline', 'Spline')], require=False)), ('legend', wagtail.core.blocks.CharBlock(default='', required=False)), ('x_axis_config', datasheet.blocks.JSONTextBlock(default='{}', required=False)), ('y_axis_config', datasheet.blocks.JSONTextBlock(default='{}', required=False)), ('chart_values', datasheet.blocks.JSONTextBlock(default='[]', required=True))))))))), ('video', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(required=False)), ('bookmark', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.TextBlock())))), ('embed_3d', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('uuid', wagtail.core.blocks.CharBlock()), ('share_link', wagtail.core.blocks.TextBlock())))), ('pdf', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('file', wagtail.documents.blocks.DocumentChooserBlock()), ('height', wagtail.core.blocks.IntegerBlock(default=550)), ('view', wagtail.core.blocks.ChoiceBlock(choices=[('Fit', 'Fit'), ('FitH', 'FitH'), ('FitH,top', 'FitH,top'), ('FitV', 'FitV'), ('FitV,left', 'FitV,left'), ('FitB', 'FitB'), ('FitBH', 'FitBH'), ('FitBH,top', 'FitBH,top'), ('FitBV', 'FitBV'), ('FitBV,left', 'FitBV,left')], required=False)))))), blank=True),
        ),
    ]
