version: '2'

volumes:
  postgres_data_dev: {}
  webpack_node_modules: {}

services:
  postgres:
    container_name: datasheet-postgres
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      #- ./database/backups:/backups
      # You can also modify this to point to your local Dropbox location where the shared
      # backups are stored. For me this is:
      - "~/Dropbox (Big Zeta)/Development/backups/datasheet:/backups"
    environment:
      - POSTGRES_USER=datasheet_user
      - POSTGRES_DB=datasheetai
    ports:
      - "5442:5432"

  smtpd:
    container_name: datasheet-smtpd
    build: ./compose/smtpd
    ports:
      - "8026:25"

#  django:
#    container_name: datasheet-django
#    build:
#      context: .
#      dockerfile: ./compose/django/dev/Dockerfile
#    command: python /app/manage.py runserver_plus 0.0.0.0:8001
#    depends_on:
#      - postgres
#    environment:
#      - POSTGRES_USER=datasheet
#      - POSTGRES_DB=datasheet
#      - DATABASE_URL=postgres://datasheet:oman-nimbus-gunfire@postgres/datasheet
#    volumes:
#      - ./django_root:/app
#      - ./requirements:/requirements
#    ports:
#      - "8001:8001"
#    links:
#      - postgres
#      - smtpd
#
