version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  static_data: {}

services:
  postgres:
    container_name: postgres
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env
    ports:
      - "127.0.0.1:5432:5432"

  django:
    container_name: django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - static_data:/data/staticfiles

  nginx:
    container_name: nginx
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"
    volumes_from:
      - django

  redis:
    container_name: redis
    image: redis:3.0
  
