# Generated by Django 2.0.4 on 2018-04-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teconn', '0005_auto_20180418_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='page_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='teconn_index', serialize=False, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='sheetpage',
            name='page_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='teconn_sheet', serialize=False, to='wagtailcore.Page'),
        ),
    ]
