# Generated by Django 2.0.3 on 2018-04-30 06:42

import datasheet.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teconn', '0012_auto_20180430_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetpage',
            name='chart',
            field=wagtail.core.fields.StreamField((('spline', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock(require=False)), ('type', wagtail.core.blocks.CharBlock(require=False)), ('legend', wagtail.core.blocks.CharBlock(required=False)), ('x_axis', wagtail.core.blocks.CharBlock(required=False)), ('y_axis', wagtail.core.blocks.CharBlock(required=False)), ('chart_values', datasheet.blocks.JSONTextBlock(required=False))))),), blank=True),
        ),
    ]
