# Generated by Django 2.0.5 on 2018-05-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teconn', '0016_auto_20180509_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetpage',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sheetpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
