# Generated by Django 2.0.3 on 2018-05-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teconn', '0017_auto_20180507_0700'),
        ('teconn', '0014_auto_20180503_0611'),
    ]

    operations = [
    ]
