# Generated by Django 2.0.5 on 2018-05-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teconn', '0020_auto_20180531_0229'),
        ('teconn', '0020_auto_20180531_0311'),
    ]

    operations = [
    ]
