# Generated by Django 2.0.3 on 2018-03-06 22:26

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0004_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='datasheetpage',
            name='stream1',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('product_code', wagtail.core.blocks.StructBlock((('type', wagtail.core.blocks.CharBlock()), ('version', wagtail.core.blocks.CharBlock()), ('coil_version', wagtail.core.blocks.CharBlock()), ('coil_system', wagtail.core.blocks.CharBlock()), ('load_voltage', wagtail.core.blocks.CharBlock()), ('contact_material', wagtail.core.blocks.CharBlock()), ('status', wagtail.core.blocks.CharBlock()), ('connector_version', wagtail.core.blocks.CharBlock())))))),
        ),
    ]
