# Generated by Django 2.0.3 on 2018-03-08 03:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0006_auto_20180308_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetpage',
            name='stream1',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('product_code', wagtail.core.blocks.StructBlock((('type', wagtail.core.blocks.CharBlock()), ('version', wagtail.core.blocks.CharBlock()), ('coil_version', wagtail.core.blocks.CharBlock()), ('coil_system', wagtail.core.blocks.CharBlock()), ('load_voltage', wagtail.core.blocks.CharBlock()), ('contact_material', wagtail.core.blocks.CharBlock()), ('status', wagtail.core.blocks.CharBlock()), ('connector_version', wagtail.core.blocks.CharBlock())))), ('carousel', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('alt', wagtail.core.blocks.CharBlock()))))), ('carousel_stream', wagtail.core.blocks.StreamBlock((('image', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('alt', wagtail.core.blocks.CharBlock())))), ('embed', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()))))))), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(label='feature'))))),
        ),
    ]
