# Generated by Django 2.0.3 on 2018-03-10 23:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0011_auto_20180310_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetpage',
            name='carousel',
            field=wagtail.core.fields.StreamField((('image', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('alt', wagtail.core.blocks.CharBlock())))), ('embed', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()))))), blank=True),
        ),
    ]
