# Generated by Django 2.0.3 on 2018-03-11 17:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0013_auto_20180311_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetpage',
            name='carousel',
            field=wagtail.core.fields.StreamField((('image', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('alt', wagtail.core.blocks.CharBlock(required=False))))), ('embed', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('width', wagtail.core.blocks.IntegerBlock(required=False)), ('height', wagtail.core.blocks.IntegerBlock(required=False)), ('allow_fullscreen', wagtail.core.blocks.BooleanBlock(default=False))))), ('fusion360', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('width', wagtail.core.blocks.IntegerBlock(required=False)), ('height', wagtail.core.blocks.IntegerBlock(required=False)), ('allow_fullscreen', wagtail.core.blocks.BooleanBlock(default=False)))))), blank=True),
        ),
    ]
