# Generated by Django 2.0.3 on 2018-03-28 22:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('datasheet', '0022_auto_20180323_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetindexpage',
            name='banner_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='datasheetindexpage',
            name='page_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='datasheetindexpage',
            name='primary_color',
            field=models.CharField(default='#000', max_length=20),
        ),
        migrations.AlterField(
            model_name='datasheetpage',
            name='attributes',
            field=wagtail.core.fields.StreamField((('features', wagtail.core.blocks.StructBlock((('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic']))),))), ('applications', wagtail.core.blocks.StructBlock((('applications', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic']))),)))), blank=True),
        ),
        migrations.AlterField(
            model_name='datasheetpage',
            name='stream1',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title', template='datasheet/blocks/heading.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('product_code', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('type', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.CharBlock()), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('key', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())), form_template='datasheet/blocks/editing/common/struct_inline.html'), required=False))))), ('relay_version', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.CharBlock()), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('key', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())), form_template='datasheet/blocks/editing/common/struct_inline.html'), required=False))))), ('coil_version', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.CharBlock()), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('key', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())), form_template='datasheet/blocks/editing/common/struct_inline.html'), required=False))))), ('coil_system', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.CharBlock()), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('key', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())), form_template='datasheet/blocks/editing/common/struct_inline.html'), required=False))))), ('load_voltage', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.CharBlock()), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('key', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())), form_template='datasheet/blocks/editing/common/struct_inline.html'), required=False))))), ('contact_material', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.CharBlock()), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('key', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())), form_template='datasheet/blocks/editing/common/struct_inline.html'), required=False))))), ('status_monitoring', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.CharBlock()), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('key', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())), form_template='datasheet/blocks/editing/common/struct_inline.html'), required=False))))), ('coil_connector_version', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.CharBlock()), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('key', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())), form_template='datasheet/blocks/editing/common/struct_inline.html'), required=False))))), ('code_table', wagtail.contrib.table_block.blocks.TableBlock({'colHeaders': True, 'startCols': 7, 'startRows': 1}))))), ('carousel', wagtail.core.blocks.StreamBlock((('image', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('alt', wagtail.core.blocks.CharBlock(required=False)), ('width', wagtail.core.blocks.IntegerBlock(required=False)), ('height', wagtail.core.blocks.IntegerBlock(required=False))))), ('embed', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('width', wagtail.core.blocks.IntegerBlock(required=False)), ('height', wagtail.core.blocks.IntegerBlock(required=False)), ('allow_fullscreen', wagtail.core.blocks.BooleanBlock(default=False))))), ('fusion360', wagtail.core.blocks.StructBlock((('subtitle', wagtail.core.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('width', wagtail.core.blocks.IntegerBlock(required=False)), ('height', wagtail.core.blocks.IntegerBlock(required=False)), ('allow_fullscreen', wagtail.core.blocks.BooleanBlock(default=False)))))))), ('dimension', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())))), ('contact_data', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('data', wagtail.contrib.table_block.blocks.TableBlock(table_options={'colHeaders': True, 'editor': 'handsontable', 'startCols': 2, 'startRows': 1}))))), ('coil_data', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('coils', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock()), ('data_table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'colHeaders': True})), ('image_title', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())))))))), ('revisions', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('data', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('date', wagtail.core.blocks.DateBlock()), ('revisions', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock())), form_template='datasheet/blocks/editing/common/struct_inline.html')))))))), form_classname='revision-block', template='datasheet/blocks/revision.html')))),
        ),
    ]
