# Generated by Django 2.0.3 on 2018-04-02 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0023_auto_20180328_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetindexpage',
            name='svglogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
