# Generated by Django 2.0.3 on 2018-04-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0026_auto_20180404_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetpage',
            name='part_number',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
