# Generated by Django 2.0.3 on 2018-04-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('datasheet', '0029_auto_20180416_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetindexpage',
            name='banner_mark',
        ),
        migrations.RemoveField(
            model_name='datasheetindexpage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='datasheetindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='datasheetpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='datasheetpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='datasheetpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='datasheetpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='features',
            name='page',
        ),
        migrations.RemoveField(
            model_name='relatedlinks',
            name='page',
        ),
        migrations.DeleteModel(
            name='Revisions',
        ),
        migrations.DeleteModel(
            name='DatasheetIndexPage',
        ),
        migrations.DeleteModel(
            name='DatasheetPage',
        ),
        migrations.DeleteModel(
            name='DatasheetPageTag',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='RelatedLinks',
        ),
    ]
