# Generated by Django 2.0.3 on 2018-04-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0031_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chat_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
