# Generated by Django 2.0.5 on 2018-05-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0032_sitesettings_chat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='active_area_background_color',
            field=models.CharField(default='#ddd', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tile_background_color',
            field=models.CharField(default='#000', max_length=20),
        ),
    ]
