# Generated by Django 2.0.5 on 2018-07-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0033_auto_20180509_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ga_tracking_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
