# Generated by Django 2.0.5 on 2018-06-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0033_auto_20180509_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_min_height',
            field=models.CharField(default='350', max_length=20),
        ),
    ]
