# Generated by Django 2.0.7 on 2018-07-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0034_sitesettings_ga_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_distributor',
            field=models.BooleanField(default=False),
        ),
    ]
