# Generated by Django 2.0.7 on 2018-08-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0035_sitesettings_is_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='desktop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tablet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
