# Generated by Django 2.0.5 on 2018-06-25 05:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('epcos', '0007_auto_20180601_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetpage',
            name='attributes',
            field=wagtail.core.fields.StreamField([('features', wagtail.core.blocks.StructBlock([('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'])))])), ('applications', wagtail.core.blocks.StructBlock([('applications', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'])))])), ('construction', wagtail.core.blocks.StructBlock([('construction', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'])))]))], blank=True),
        ),
    ]
