# Generated by Django 2.0.6 on 2018-07-03 03:20

import datasheet.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('microchip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetSubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('stream', wagtail.core.fields.StreamField([('dimension', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('enabled_drawing', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('characteristics', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Characteristics')), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('bookmark', wagtail.core.blocks.CharBlock(default='characteristics')), ('charts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='', required=False)), ('subtitle', wagtail.core.blocks.CharBlock(default='', require=False)), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('bar', 'Bar'), ('column', 'Column'), ('line', 'Line'), ('spline', 'Spline'), ('area', 'Area')], require=False)), ('legend', wagtail.core.blocks.CharBlock(default='', required=False)), ('x_axis_config', datasheet.blocks.JSONTextBlock(default='{}', required=False)), ('y_axis_config', datasheet.blocks.JSONTextBlock(default='{}', required=False)), ('chart_values', datasheet.blocks.JSONTextBlock(default='[]', required=True))])))])), ('chart', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock(require=False)), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('bar', 'Bar'), ('column', 'Column'), ('line', 'Line'), ('spline', 'Spline'), ('area', 'Area')], require=False)), ('legend', wagtail.core.blocks.CharBlock(required=False)), ('x_axis', wagtail.core.blocks.CharBlock(required=False)), ('y_axis', wagtail.core.blocks.CharBlock(required=False)), ('chart_values', datasheet.blocks.JSONTextBlock(required=False))])), ('video', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('bookmark', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.TextBlock())])), ('embed_3d', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('uuid', wagtail.core.blocks.CharBlock()), ('share_link', wagtail.core.blocks.TextBlock())])), ('grid', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('json_data', datasheet.blocks.JSONTextBlock(required=False))])), ('pdf', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('file', wagtail.documents.blocks.DocumentChooserBlock()), ('height', wagtail.core.blocks.IntegerBlock(default=550)), ('view', wagtail.core.blocks.ChoiceBlock(choices=[('Fit', 'Fit'), ('FitH', 'FitH'), ('FitH,top', 'FitH,top'), ('FitV', 'FitV'), ('FitV,left', 'FitV,left'), ('FitB', 'FitB'), ('FitBH', 'FitBH'), ('FitBH,top', 'FitBH,top'), ('FitBV', 'FitBV'), ('FitBV,left', 'FitBV,left')], required=False))])), ('richtext', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('bookmark', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock())]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
