# Generated by Django 2.0.7 on 2018-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microchip', '0002_sheetsubpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsubpage',
            name='section_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
