# Generated by Django 2.0.7 on 2018-07-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microchip', '0003_sheetsubpage_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsubpage',
            name='pdf_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
