# Generated by Django 2.0.7 on 2018-07-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microchip', '0005_auto_20180716_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsubpage',
            name='title_raw',
            field=models.CharField(default='update me', help_text="The page title as you'd like it to be seen by the public, without the prefix", max_length=255, verbose_name='title_raw'),
            preserve_default=False,
        ),
    ]
