# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 19:32
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0002_datasheetindexpage_svglogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheetindexpage',
            options={'verbose_name': 'Datasheet Index'},
        ),
        migrations.AddField(
            model_name='datasheetpage',
            name='stream1',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())), default=''),
            preserve_default=False,
        ),
    ]
